spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:doc_flow_db
    username: sa
    password:
  liquibase:
#    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled:  false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

