spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:doc_flow_db'
    username: sa
    password: ''
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB